/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_voltdb_utils_DBBPool */

#ifndef _Included_org_voltdb_utils_DBBPool
#define _Included_org_voltdb_utils_DBBPool
#ifdef __cplusplus
extern "C" {
#endif
#undef org_voltdb_utils_DBBPool_traceAllocations
#define org_voltdb_utils_DBBPool_traceAllocations 1L
#undef org_voltdb_utils_DBBPool_MAX_ALLOCATION_SIZE
#define org_voltdb_utils_DBBPool_MAX_ALLOCATION_SIZE 262144L
#undef org_voltdb_utils_DBBPool_m_defaultMaxArenaSize
#define org_voltdb_utils_DBBPool_m_defaultMaxArenaSize 67108864L
/*
 * Class:     org_voltdb_utils_DBBPool
 * Method:    getBufferAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_org_voltdb_utils_DBBPool_getBufferAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_voltdb_utils_DBBPool
 * Method:    getBufferCRC32
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_org_voltdb_utils_DBBPool_getBufferCRC32
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
